import os
from pathlib import Path
from datetime import datetime
from typing import Optional

from models import WorkflowSession, InteractionLog, Assessment, AphoristicorResponse


class MarkdownLogger:
    def __init__(self, logs_dir: str = "logs"):
        self.logs_dir = Path(logs_dir)
        self.logs_dir.mkdir(exist_ok=True)
        self.current_log_file: Optional[Path] = None
        
    def initialize_log(self, filename: str, session: WorkflowSession) -> None:
        self.current_log_file = self.logs_dir / filename
        
        header = f"""# Philosophical Statement Refinement Session

## Session Information
- **Session ID**: {session.session_id}
- **Started**: {session.started_at.strftime("%Y-%m-%d %H:%M:%S")}
- **Initial Statement**: "{session.initial_statement}"
- **Target Ranking**: {session.target_ranking}/10
- **Max Iterations**: {session.max_iterations}

---

## Refinement Process

"""
        
        with open(self.current_log_file, 'w', encoding='utf-8') as f:
            f.write(header)
    
    def log_assessment(self, assessment: Assessment, iteration: int) -> None:
        if not self.current_log_file:
            return
            
        content = f"""
### Iteration {iteration} - Assessment

**Timestamp**: {assessment.timestamp.strftime("%Y-%m-%d %H:%M:%S")}  
**Ranking**: {assessment.ranking}/10

#### Overview
{assessment.overview}

#### Strengths
"""
        
        for strength in assessment.strengths:
            content += f"- {strength}\n"
            
        content += "\n#### Weaknesses\n"
        for weakness in assessment.weaknesses:
            content += f"- {weakness}\n"
            
        content += f"\n#### Detailed Reasoning\n{assessment.reasoning}\n"
        
        with open(self.current_log_file, 'a', encoding='utf-8') as f:
            f.write(content)
    
    def log_refinement(self, response: AphoristicorResponse, iteration: int) -> None:
        if not self.current_log_file:
            return
            
        content = f"""
### Iteration {iteration} - Refinement

#### Refined Statement
> "{response.refined_statement}"

#### Explanation of Changes
{response.explanation}

---
"""
        
        with open(self.current_log_file, 'a', encoding='utf-8') as f:
            f.write(content)
    
    def log_interaction(self, interaction: InteractionLog) -> None:
        if not self.current_log_file:
            return
        
        # This method can be used for additional interaction-specific logging
        # Currently, the assessment and refinement methods handle the main content
        pass
    
    def log_completion(self, session: WorkflowSession) -> None:
        if not self.current_log_file:
            return
            
        completion_time = session.completed_at.strftime("%Y-%m-%d %H:%M:%S") if session.completed_at else "N/A"
        
        content = f"""
## Session Completion

- **Completed**: {completion_time}
- **Total Iterations**: {session.current_iteration}
- **Final Ranking**: {session.final_ranking}/10
- **Completion Reason**: {session.completion_reason}
- **Final Statement**: "{session.current_statement}"

## Summary Statistics

- **Initial Statement**: "{session.initial_statement}"
- **Final Statement**: "{session.current_statement}"
- **Improvement**: {session.final_ranking if session.final_ranking else 'N/A'}/10 rating achieved
- **Duration**: {session.current_iteration} iterations
- **Success**: {"✅ Yes" if session.final_ranking and session.final_ranking >= session.target_ranking else "❌ No"}

---

*Generated by Thinkers Dinning - Philosophical Statement Refinement Workflow*
*Session ID: {session.session_id}*
"""
        
        with open(self.current_log_file, 'a', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Complete session log saved to: {self.current_log_file}")
    
    def get_log_path(self) -> Optional[Path]:
        return self.current_log_file